# Generated by Django 2.1.3 on 2019-08-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Arrived'), ('P', 'Processed'), ('D', 'Deprecated')], max_length=120, null=True)),
                ('report_type', models.CharField(blank=True, max_length=120, null=True)),
                ('account', models.CharField(blank=True, max_length=120, null=True)),
                ('trade_date', models.CharField(blank=True, max_length=120, null=True)),
                ('generation_time', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterpartyShor', models.CharField(blank=True, db_column='CounterpartyShor', max_length=30, null=True)),
                ('TradeID', models.CharField(blank=True, db_column='TradeID', max_length=30, null=True)),
                ('TradeDate', models.CharField(blank=True, db_column='TradeDate', max_length=30, null=True)),
                ('SettlementDate', models.CharField(blank=True, db_column='SettlementDate', max_length=30, null=True)),
                ('Ticker', models.CharField(blank=True, db_column='Ticker', max_length=30, null=True)),
                ('ISIN', models.CharField(blank=True, db_column='ISIN', max_length=30, null=True)),
                ('Name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('ProductShortName', models.CharField(blank=True, db_column='ProductShortName', max_length=30, null=True)),
                ('StrategyExternalID', models.CharField(blank=True, db_column='Strategy(ExternalID)', max_length=30, null=True)),
                ('Qty', models.CharField(blank=True, db_column='Qty', max_length=30, null=True)),
                ('Type', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
                ('CCYUnderlying', models.CharField(blank=True, db_column='CCYUnderlying', max_length=30, null=True)),
                ('GrossPriceLocal', models.CharField(blank=True, db_column='GrossPrice(Local)', max_length=30, null=True)),
                ('FXRate', models.CharField(blank=True, db_column='FXRate', max_length=30, null=True)),
                ('GrossPriceSwap', models.CharField(blank=True, db_column='GrossPriceSwap', max_length=30, null=True)),
                ('Comms', models.CharField(blank=True, db_column='Comms', max_length=30, null=True)),
                ('MarketCharges', models.CharField(blank=True, db_column='MarketCharges', max_length=30, null=True)),
                ('NetPriceSwap', models.CharField(blank=True, db_column='NetPriceSwap', max_length=30, null=True)),
                ('SwapCCY', models.CharField(blank=True, db_column='SwapCCY', max_length=30, null=True)),
                ('TradedNotionalAmt', models.CharField(blank=True, db_column='TradedNotionalAmt', max_length=30, null=True)),
                ('FundingRate', models.CharField(blank=True, db_column='FundingRate', max_length=30, null=True)),
                ('Spread', models.CharField(blank=True, db_column='Spread', max_length=30, null=True)),
                ('Performance', models.CharField(blank=True, db_column='Performance', max_length=30, null=True)),
                ('FundingReset', models.CharField(blank=True, db_column='FundingReset', max_length=30, null=True)),
                ('DividendEntitlement', models.CharField(blank=True, db_column='DividendEntitlement', max_length=30, null=True)),
                ('InitialMargin', models.CharField(blank=True, db_column='InitialMargin', max_length=30, null=True)),
                ('ProductType', models.CharField(blank=True, db_column='ProductType', max_length=30, null=True)),
                ('RemainingNotionalAmt', models.CharField(blank=True, db_column='RemainingNotionalAmt', max_length=30, null=True)),
                ('UniqueTransactionID', models.CharField(blank=True, db_column='Unique Transaction ID', max_length=30, null=True)),
                ('TradeTime', models.CharField(blank=True, db_column='TradeTime', max_length=30, null=True)),
                ('TotalComm', models.CharField(blank=True, db_column='TotalComm', max_length=30, null=True)),
                ('TotalMarket', models.CharField(blank=True, db_column='TotalMarket', max_length=30, null=True)),
                ('OrderIns', models.CharField(blank=True, db_column='OrderIns', max_length=30, null=True)),
                ('InstrumentIdentifier', models.CharField(blank=True, db_column='InstrumentIdentifier', max_length=30, null=True)),
                ('Venue', models.CharField(blank=True, db_column='Venue', max_length=30, null=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_files.ProcessedFiles')),
            ],
        ),
        migrations.DeleteModel(
            name='ThreadTask',
        ),
    ]
