# Generated by Django 2.1.3 on 2019-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_files', '0002_auto_20190808_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfiles',
            name='modification_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='processedfiles',
            name='status',
            field=models.CharField(blank=True, choices=[('Arrived', 'Arrived'), ('Processed', 'Processed'), ('Deprecated', 'Deprecated')], max_length=120, null=True),
        ),
    ]
